[package]
name = "eventsource"
version = "0.1.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]

description = "Library for accessing EventSource/Server-Sent Events endpoints"
repository = "https://github.com/lluchs/eventsource"
license = "MIT"
keywords = ["http"]

[dependencies]
hyper = "0.9"
